[[redirects]]
  from = "https://sunandstone.us/*"
  to = "https://sanandstone.us/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.sunandstone.us/*"
  to = "https://sanandstone.us/:splat"
  status = 301
  force = true